{\rtf1\ansi\ansicpg1252\cocoartf2759
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 apiVersion: apps/v1\
kind: Deployment\
metadata:\
  name: \{\{ include "springboot-helm-chart.fullname" . \}\}\
  labels:\
    \{\{- include "springboot-helm-chart.labels" . | nindent 4 \}\}\
spec:\
  \{\{- if not .Values.autoscaling.enabled \}\}\
  replicas: \{\{ .Values.replicaCount \}\}\
  \{\{- end \}\}\
  selector:\
    matchLabels:\
      \{\{- include "springboot-helm-chart.selectorLabels" . | nindent 6 \}\}\
  template:\
    metadata:\
      annotations:\
        checksum/config: \{\{ .Values.properties | quote | sha256sum \}\}\
      \{\{- with .Values.podAnnotations \}\}\
        \{\{- toYaml . | nindent 8 \}\}\
      \{\{- end \}\}\
      labels:\
        \{\{- include "springboot-helm-chart.selectorLabels" . | nindent 8 \}\}\
    spec:\
      \{\{- with .Values.imagePullSecrets \}\}\
      imagePullSecrets:\
        \{\{- toYaml . | nindent 8 \}\}\
      \{\{- end \}\}\
      serviceAccountName: \{\{ include "springboot-helm-chart.serviceAccountName" . \}\}\
      securityContext:\
        \{\{- toYaml .Values.podSecurityContext | nindent 8 \}\}\
      containers:\
        - name: \{\{ .Chart.Name \}\}\
          securityContext:\
            \{\{- toYaml .Values.securityContext | nindent 12 \}\}\
          image: "\{\{ .Values.image.repository \}\}:\{\{ .Values.image.tag | default .Chart.AppVersion \}\}"\
          imagePullPolicy: \{\{ .Values.image.pullPolicy \}\}\
          ports:\
            - name: http\
              containerPort: \{\{ .Values.service.port \}\}\
              protocol: TCP\
          livenessProbe:\
            httpGet:\
              path: /actuator/health/liveness  \
              port: http\
          readinessProbe:\
            httpGet:\
              path: /actuator/health/readiness\
              port: http\
          resources:\
            \{\{- toYaml .Values.resources | nindent 12 \}\}\
          envFrom:\
            - configMapRef:\
                name: \{\{ include "springboot-helm-chart.fullname" . \}\}\
            \{\{- range .Values.secretRef \}\}\
            - secretRef: \
                name: \{\{ . \}\}\
            \{\{- end \}\}\
      \{\{- with .Values.nodeSelector \}\}\
      nodeSelector:\
        \{\{- toYaml . | nindent 8 \}\}\
      \{\{- end \}\}\
      \{\{- with .Values.affinity \}\}\
      affinity:\
        \{\{- toYaml . | nindent 8 \}\}\
      \{\{- end \}\}\
      \{\{- with .Values.tolerations \}\}\
      tolerations:\
        \{\{- toYaml . | nindent 8 \}\}\
      \{\{- end \}\}}