{\rtf1\ansi\ansicpg1252\cocoartf2759
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 \{\{- if .Values.ingress.enabled -\}\}\
\{\{- $fullName := include "springboot-helm-chart.fullname" . -\}\}\
\{\{- $svcPort := .Values.service.port -\}\}\
\{\{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) \}\}\
  \{\{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") \}\}\
  \{\{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className\}\}\
  \{\{- end \}\}\
\{\{- end \}\}\
\{\{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -\}\}\
apiVersion: networking.k8s.io/v1\
\{\{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -\}\}\
apiVersion: networking.k8s.io/v1beta1\
\{\{- else -\}\}\
apiVersion: extensions/v1beta1\
\{\{- end \}\}\
kind: Ingress\
metadata:\
  name: \{\{ $fullName \}\}\
  labels:\
    \{\{- include "springboot-helm-chart.labels" . | nindent 4 \}\}\
  \{\{- with .Values.ingress.annotations \}\}\
  annotations:\
    \{\{- toYaml . | nindent 4 \}\}\
  \{\{- end \}\}\
spec:\
  \{\{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) \}\}\
  ingressClassName: \{\{ .Values.ingress.className \}\}\
  \{\{- end \}\}\
  \{\{- if .Values.ingress.tls \}\}\
  tls:\
    \{\{- range .Values.ingress.tls \}\}\
    - hosts:\
        \{\{- range .hosts \}\}\
        - \{\{ . | quote \}\}\
        \{\{- end \}\}\
      secretName: \{\{ .secretName \}\}\
    \{\{- end \}\}\
  \{\{- end \}\}\
  rules:\
    \{\{- range .Values.ingress.hosts \}\}\
    - host: \{\{ .host | quote \}\}\
      http:\
        paths:\
          \{\{- range .paths \}\}\
          - path: \{\{ .path \}\}\
            \{\{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) \}\}\
            pathType: \{\{ .pathType \}\}\
            \{\{- end \}\}\
            backend:\
              \{\{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion \}\}\
              service:\
                name: \{\{ $fullName \}\}\
                port:\
                  number: \{\{ $svcPort \}\}\
              \{\{- else \}\}\
              serviceName: \{\{ $fullName \}\}\
              servicePort: \{\{ $svcPort \}\}\
              \{\{- end \}\}\
          \{\{- end \}\}\
    \{\{- end \}\}\
\{\{- end \}\}}