{\rtf1\ansi\ansicpg1252\cocoartf2759
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 # Default values for springboot-helm-chart.\
\
\
replicaCount: 1\
\
properties:\
  welcome.text: Hello world.\
  nav.bgcolor: lightblue\
\
\
secretRef: []\
\
image:\
  repository: public.ecr.aws/k8s-demo-app\
  pullPolicy: IfNotPresent\
  tag: ""\
\
imagePullSecrets: []\
nameOverride: ""\
fullnameOverride: ""\
\
serviceAccount:\
  create: true\
  annotations: \{\}\
  name: ""\
\
podAnnotations: \{\}\
\
podSecurityContext: \{\}\
  # fsGroup: 2000\
\
securityContext: \{\}\
  # capabilities:\
  #   drop:\
  #   - ALL\
  # readOnlyRootFilesystem: true\
  # runAsNonRoot: true\
  # runAsUser: 1000\
\
service:\
  type: ClusterIP\
  port: 8080\
\
ingress:\
  enabled: false\
  className: ""\
  annotations: \{\}\
    # kubernetes.io/ingress.class: nginx\
    # kubernetes.io/tls-acme: "true"\
  hosts:\
    - host: chart-example.local\
      paths:\
        - path: /\
          pathType: ImplementationSpecific\
  tls: []\
  #  - secretName: chart-example-tls\
  #    hosts:\
  #      - chart-example.local\
\
resources: \{\}\
  # limits:\
  #   cpu: 100m\
  #   memory: 128Mi\
  # requests:\
  #   cpu: 100m\
  #   memory: 128Mi\
\
autoscaling:\
  enabled: false\
  minReplicas: 1\
  maxReplicas: 100\
  targetCPUUtilizationPercentage: 80\
  # targetMemoryUtilizationPercentage: 80\
\
nodeSelector: \{\}\
\
tolerations: []\
\
affinity: \{\}}